Regrid2#15
CDAT/cdms pull request #120
Opened 2017-04-21 01:25 UTC by dnadeau4

Issue #5 and #15 are in this  pull request.

2017-04-21 01:42 UTC, dnadeau4 commented
Fix #15

2017-04-24 14:10 UTC, doutriaux1 commented
@dnadeau4 opened or closed? It's not merged!

2017-04-26 17:56 UTC, dnadeau4 commented
I think my comment closed it by mistake.

2017-04-26 17:56 UTC, dnadeau4 commented
Please merge @doutriaux1

2017-04-26 18:01 UTC, doutriaux1 requested changes

2017-04-26 18:01 UTC, doutriaux1 commented on tests/test_gen_grid.py
> +import pdb
nope!

2017-04-26 18:01 UTC, doutriaux1 commented on tests/test_regrid2.py
> +from regrid2 import Horizontal
why did we change this? Shouldn't we have 2 tests?

2017-04-29 00:12 UTC, dnadeau4 commented on tests/test_regrid2.py
> +from regrid2 import Horizontal
Because of this warning.
https://github.com/UV-CDAT/cdms/blob/master/regrid2/Lib/horizontal.py#L291-L294

2017-05-01 16:45 UTC, merged